### ISSUE TITLE
Token获取异常

### ISSUE THREAD

**Issue by mr-cn** [SSmJaE/UnipusHelper#1]
![图片](https://user-images.githubusercontent.com/19818121/99414502-d9413e00-2931-11eb-8593-8281cfe49299.png)

Warning：
VM411:34 GM_xmlhttpRequest: SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at f (eval at exec_fn (pc.html?cid=293954:1), <anonymous>:31:203)
    at Object.response (eval at exec_fn (pc.html?cid=293954:1), <anonymous>:34:86)
    at Function.get (eval at exec_fn (pc.html?cid=293954:1), <anonymous>:34:401)

Error：
 Uncaught (in promise) TypeError: Cannot read property 'openId' of undefined

请问如何Debug？盲猜是请求Token接口返回的数据格式不同，但是没看出是哪个请求

**Comment by SSmJaE** [comment]
> ![图片](https://user-images.githubusercontent.com/19818121/99414502-d9413e00-2931-11eb-8593-8281cfe49299.png)
> 
> Warning：
> VM411:34 GM_xmlhttpRequest: SyntaxError: Unexpected token < in JSON at position 0
> at parse ()
> at f (eval at exec_fn (pc.html?cid=293954:1), :31:203)
> at Object.response (eval at exec_fn (pc.html?cid=293954:1), :34:86)
> at Function.get (eval at exec_fn (pc.html?cid=293954:1), :34:401)
> 
> Error：
> Uncaught (in promise) TypeError: Cannot read property 'openId' of undefined
> 
> 请问如何Debug？盲猜是请求Token接口返回的数据格式不同，但是没看出是哪个请求

获取token的请求是requests.ts下的getToken方法，调用的是官方接口获取openId，我也不太清楚为什么有时会获取异常，这个方法被requestErrorHandler装饰器包裹，会在方法调用出错时自动在悬浮窗中输出“token获取异常”
看起来是官方接口返回的响应有问题(解析json之后没有openId属性)，我自己的账号没有遇到过，如果你能提供稳定复现的方法的话，也许可以解决
一般来说，重新登录可以解决这个问题
