### ISSUE TITLE
[Bug Report]问题反馈

### ISSUE THREAD

**Issue by raingnight** [SSmJaE/UnipusHelper#11]
公众号搜索不到了

**Comment by sasaju** [comment]
> 公众号搜索不到了
> 

公众号迁移到了“四六级考试必过”，但是这个公众号无法绑定![Screenshot_2021-05-16-13-29-10-544_com.tencent.mm.jpg](https://user-images.githubusercontent.com/21136684/118386544-bb3b6880-b64a-11eb-9a0a-8e12a43ec1c9.jpg)
