### ISSUE TITLE
Releases中0.0.1

### ISSUE THREAD

**Issue by Boyka-SS** [SSmJaE/UnipusHelper#2]
你好，为啥，我在那个里面没找到0.01版本的呢

**Comment by SSmJaE** [comment]
此项目最初名为U艹/U++改，源代码直接发布在greasyfork上
之后使用typescript重构，改名Unipus网课助手，只发布了0.0.1一个版本
0.0.1是直接发布在greasyFork上的，可以在gf的历史版本中找到
再之后与另一个作者[DanDan](https://github.com/Dandanla)的脚本合并，改名U校园网课助手，1.0.0-1.1.2是这位作者所写，只有1.2.0之后的版本是我经手的

版本历史具体可见(按时间顺序)
[U艹](https://github.com/SSmJaE/UnipusHelper/blob/master/docs/CHANGELOG%20of%20U%E8%89%B9.md)
[0.0.1](https://github.com/SSmJaE/UnipusHelper/blob/master/docs/CHANGELOG%20of%20UnipusHelper%20old%20version.md)
[当前版本](https://github.com/SSmJaE/UnipusHelper/blob/master/docs/CHANGELOG.md)

如果是为了学习源码
U艹(即未用Typescript重构)的源码在https://github.com/SSmJaE/MyUserScripts/tree/master/U%E6%A0%A1%E5%9B%AD%E7%AD%94%E6%A1%88%E8%89%B9
架构和0.0.1相同的WELearnHelper的0.8.0版本
https://github.com/SSmJaE/WELearnHelper
