### ISSUE TITLE
填空题可能出现自动粘贴后提示未完成的情况，在手动剪切粘贴后恢复

### ISSUE THREAD

**Issue by ghost** [SSmJaE/UnipusHelper#3]

**Comment by SSmJaE** [comment]
指的是
1.自动答题之后提示未完成？
2.粘贴通过自动复制功能复制(即点击消息自动复制)的答案，提示未完成？
的那种情况呢？

使用的版本是哪个？
使用的是什么浏览器？
具体是哪个课程的哪个章节？

方便提供账号，以进行调试吗？

**Comment by alissa42** [comment]
- 自动答题之后提示未完成
- Chromium 87.0.4280.88 Arch Linux
- 新视野大学英语（第三版）视听说 3 && 新视野大学英语（第三版）视听说 2

**Comment by sasaju** [comment]
油猴插件自动答题之后 点击提交提示未完成
Windows-Chrome  87.0.4280.88（正式版本） （64 位）
新视野大学英语（第三版）读写译3

**Comment by sasaju** [comment]
附图如下
![image](https://user-images.githubusercontent.com/21136684/102043299-07218180-3e0f-11eb-9496-718f8959b444.png)
![image](https://user-images.githubusercontent.com/21136684/102043328-1274ad00-3e0f-11eb-9a35-8a75924d4b29.png)

**Comment by SSmJaE** [comment]
原因是，未能正常触发input的事件
很奇怪的一点是，1.3.3的实现，在某些练习中，可以正常触发事件，而另一些则不行
我手头只有自己的账号，没法测试各种题型，如果方便的话，可以通过qq群向我提供账号以测试
最近比较忙，如果有能力解决的话，欢迎提交pr
相关代码实现为src/plugins/exercise/solver.ts中的handleInput函数
关于answerSheetType和answerNetType，可以打开控制台查看，如果能提供这两个信息，会很有助于问题的解决
