### ISSUE TITLE
U校园助手相关

### ISSUE THREAD

**Issue by nm1298780355** [SSmJaE/UnipusHelper#9]
刷时长功能支持的时长范围是多少？
我设置成90分钟跳转一次，但是实际不到10分钟就自动跳转页面。

**Comment by SSmJaE** [comment]
官方设定是30分钟就停止计时，不要大于30分钟
一般建议10分钟以内，配合范围刷+循环刷以实现增加指定单元时长
10分钟就切换，可能是因为开启了随机时长
